version: "3.7"
services:
  database:
    image: docker.io/bitnami/mariadb:10.1.37
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=dev
      - MARIADB_USER=dev
      - MARIADB_PASSWORD=dev
    ports:
      - 3306:3306
    volumes:
      - mariadb:/bitnami/mariadb
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
      - PMA_USER=dev
      - PMA_PASSWORD=dev
volumes:
  mariadb:
    driver: local
